# Generated by Django 5.0.6 on 2024-11-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
    ]
