# Generated by Django 5.0.6 on 2024-11-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='course_id',
            new_name='course',
        ),
    ]
