# Generated by Django 5.0.6 on 2024-11-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_course_id_subscription_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='course',
            new_name='course_id',
        ),
    ]
