# Generated by Django 5.0.6 on 2024-11-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_course_pay_id_lesson_pay_id'),
        ('users', '0010_rename_course_subscription_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lesson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lesson', verbose_name='урок'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='курс'),
        ),
    ]
