# Generated by Django 5.0.6 on 2024-11-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subscription_lesson_id_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pay_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id сессии оплаты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pay_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка оплаты'),
        ),
    ]
