# Generated by Django 5.0.6 on 2024-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус оплаты'),
        ),
    ]
