# Generated by Django 5.0.6 on 2024-11-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_subscription_pay_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
