# Generated by Django 5.0.6 on 2024-07-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
