# Generated by Django 5.0.6 on 2024-11-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lesson_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id продукта в stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id продукта в stripe'),
        ),
    ]
