# Generated by Django 5.0.6 on 2024-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_course_product_id_lesson_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены в stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены в stripe'),
        ),
    ]
