# Generated by Django 5.0.6 on 2024-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_price_id_lesson_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pay_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id сессии оплаты'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pay_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id сессии оплаты'),
        ),
    ]
