# Generated by Django 5.0.6 on 2024-11-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_course_pay_id_lesson_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='usd_price',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='цена в $'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='usd_price',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='цена в $'),
        ),
    ]
